language: go
sudo: required

services:
  - docker
go:
  - "1.9"
  - "1.10"

env:
  - DEP_VERSION="0.4.1"

before_install:
  # add dep for dependency management
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

script:
  - make test

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
